### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by zhouyijiaren** [cloudinsight/cloudinsight-agent#4]
我想知道，这东西支持从agent返回数据吗，我只想获得数据，不想用cloudinsight自己的前端。
我要做的是一个课程项目。

**Comment by startover** [comment]
暂时还办不到，目前 agent 端并没有自己存储数据，收集到的数据会立即发到 Cloudinsight 后端，您可以 fork 一个版本，再按照您那边的需求进行定制化修改。

**Comment by zhouyijiaren** [comment]
ok,谢谢
