### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by AnnyGao** [cloudinsight/cloudinsight-agent#6]
$ mkdir -p $GOPATH/src/github.com/cloudinsight
$ cd $GOPATH/src/github.com/cloudinsight
$ git clone https://github.com/cloudinsight/cloudinsight-agent
$ cd cloudinsight-agent
$ make build

I have done steps follow the instruction as above, build should be successful, but I got below error, build failed.

collector/plugins/docker/docker.go:4:2: cannot find package "context" in any of:
	/usr/local/goexport/src/github.com/cloudinsight/cloudinsight-agent/vendor/context (vendor tree)
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/usr/local/goexport/src/context (from $GOPATH)
Makefile:29: recipe for target 'build' failed

OS: ubuntu 16.04. 64 bit

go version: go-1.6

please kindly help to advice where is wrong, how can I do to fix this issue, thanks

**Comment by startover** [comment]
As we support docker, and the docker engine-api package we use needs golang 1.7+, so your golang version must be 1.7+.
